[build]
  # Directory to change to before starting the build.
  base = "blender-portfolio"
  
  # Directory (relative to the base directory) that contains the deploy-ready HTML files.
  publish = "dist"

  # Default build command.
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
