[build]
  # Directory to change to before starting the build.
  # Since this file is in the blender-portfolio directory, 
  # if you set the "Base directory" in Netlify UI to "blender-portfolio",
  # this contextualizes the build correctly.
  base = "/"
  
  # Directory (relative to root of your repo) that contains the deploy-ready HTML files.
  publish = "dist"

  # Default build command.
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
